# Generated by Django 2.2.5 on 2020-11-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201110_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='listing_category',
            field=models.CharField(choices=[('Books', 'BOOKS'), ('Business & Industrial', 'BUSINESS & INDUSTRIAL'), ('Clothing, Shoes & Accessories', 'CLOTHING, SHOES & ACCESSORIES'), ('Collectibles', 'COLLECTIBLES'), ('Consumer Electronics', 'CONSUMER ELECTRONICS'), ('Crafts', 'CRAFTS'), ('Dolls & Bears', 'DOLLS & BEARS'), ('Home & Garden', 'HOME & GARDEN'), ('Motors', 'MOTORS'), ('Pet Supplies', 'PET SUPPLIES'), ('Sporting Goods', 'SPORTING GOODS'), ('Sports Mem, Cards & Fan Shop', 'SPORTS MEM, CARDS & FAN SHOP'), ('Toys & Hobbies', 'TOYS & HOBBIES'), ('Antiques', 'ANTIQUES'), ('Computers/Tablets & Networking', 'COMPUTERS/TABLES & NETWORKING')], default='Books', max_length=64),
        ),
    ]
