# Generated by Django 2.2.5 on 2020-11-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/auctions/images'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='listing_category',
            field=models.CharField(choices=[('1', 'BOOKS'), ('2', 'BUSINESS & INDUSTRIAL'), ('3', 'CLOTHING, SHOES & ACCESSORIES'), ('4', 'COLLECTIBLES'), ('5', 'CONSUMER ELECTRONICS'), ('6', 'CRAFTS'), ('7', 'DOLLS & BEARS'), ('8', 'HOME & GARDEN'), ('9', 'MOTORS'), ('10', 'PET SUPPLIES'), ('11', 'SPORTING GOODS'), ('12', 'SPORTS MEM, CARDS & FAN SHOP'), ('13', 'TOYS & HOBBIES'), ('14', 'ANTIQUES'), ('15', 'COMPUTERS/TABLETS & NETWORKING')], default='1', max_length=64),
        ),
    ]
