# Generated by Django 2.2.5 on 2020-11-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201110_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
