# Generated by Django 2.2.5 on 2020-11-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201112_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/uploaded'),
        ),
    ]
