# Generated by Django 2.2.5 on 2020-11-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201116_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank=True, default='media/uploaded/sticker.png', null=True, upload_to='media/uploaded'),
        ),
    ]
