# Generated by Django 2.2.5 on 2020-11-23 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201119_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user_comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='user_comment',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
