# Generated by Django 2.2.5 on 2020-11-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201123_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='vendor',
            new_name='product',
        ),
    ]
