# Generated by Django 2.2.5 on 2020-11-24 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20201124_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='potential_buyer',
        ),
        migrations.AddField(
            model_name='bids',
            name='potential_buyer',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
