# Generated by Django 2.2.5 on 2020-11-24 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20201124_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='potential_buyer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
