# Generated by Django 2.2.5 on 2020-11-29 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20201126_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='state',
            field=models.CharField(choices=[('1', 'ACTIVE'), ('2', 'NOT ACTIVE')], default='1', max_length=64),
        ),
        migrations.AlterField(
            model_name='listings',
            name='listing_category',
            field=models.CharField(choices=[('1', 'BOOKS'), ('2', 'BUSINESS & INDUSTRIAL'), ('3', 'CLOTHING, SHOES & ACCESSORIES'), ('4', 'COLLECTIBLES'), ('5', 'CONSUMER ELECTRONICS'), ('6', 'CRAFTS'), ('7', 'DOLLS & BEARS'), ('8', 'HOME & GARDEN'), ('9', 'MOTORS'), ('10', 'PET SUPPLIES'), ('11', 'SPORTING GOODS'), ('12', 'SPORTS MEM, CARDS & FAN SHOP'), ('13', 'TOYS & HOBBIES'), ('14', 'ANTIQUES'), ('15', 'COMPUTERS/TABLETS & NETWORKING')], default='1', max_length=150),
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_auction', to='auctions.Listings')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
